### ISSUE TITLE
requirement for nasm is not documented in README

### ISSUE THREAD

**Issue by gdt** [pycompression/python-isal#198]

**Comment by rhpvorderman** [comment]
Quoting the readme:

> Installation is supported on Linux, Windows and MacOS. For more advanced installation options check the [documentation](https://python-isal.readthedocs.io/en/stable/index.html#installation).

Quoting the documentation:

> Installation is supported on Linux, MacOS and Windows. On most platforms wheels are provided. The installation will include a staticallly linked version of ISA-L. If a wheel is not provided for your system the installation will build ISA-L first in a temporary directory. **Please check the [ISA-L homepage](https://github.com/intel/isa-l) for the build requirements.**

Emphasis mine

Quoting the isa-L homepage:
```
Building ISA-L
Prerequisites

    Make: GNU 'make' or 'nmake' (Windows).
    Optional: Building with autotools requires autoconf/automake/libtool packages.
    Optional: Manual generation requires help2man package.

x86_64:

    Assembler: nasm. Version 2.15 or later suggested (other versions of nasm and yasm may build but with limited function [support](https://github.com/intel/isa-l/blob/master/doc/build.md)).
    Compiler: gcc, clang, icc or VC compiler.

aarch64:

    Assembler: gas v2.24 or later.
    Compiler: gcc v4.7 or later.

other:

    Compiler: Portable base functions are available that build with most C compilers.
```

So it is mentioned. Yes, you have to dig a little. Since most of the users can use a prebuilt wheel, I think it is justified not having this on the front page.
