### ISSUE TITLE
Arm64 Support

### ISSUE THREAD

**Issue by rhpvorderman** [pycompression/python-isal#33]
ISA-L can run on ARM64, python can run on ARM64. Python-isal should therefore be able to run on ARM64 as well. Currently there is no equipment and no CI environment available to properly test this. 

If someone where to provide a self-hosted github runner to run ARM tests on this issue could be tackled.

**Comment by animalize** [comment]
See this GitHub action, it supports `aarch64`.

Need to install these manually: python3 python3-pip build-essential gcc

```yaml

      - uses: uraimo/run-on-arch-action@v2.0.9
        name: Build & run test
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          install: |
            apt-get update -q -y
            apt-get install -q -y python3 python3-pip build-essential gcc
          run: |
            python3 -c "import platform;print('Machine type:', platform.machine())"
            python3 -m pip install -U setuptools
            python3 setup.py install
            python3 tests/test_xxxx.py
```
